FROM ubuntu:24.04

#
# Skip interactive mode
#
ENV DEBIAN_FRONTEND=noninteractive

#
# Add Ondrej PPA
#
RUN apt-get update && apt-get install -y software-properties-common unzip
RUN add-apt-repository ppa:ondrej/php -y


#
# Install Nginx and latest PHP version 8.2.10
#
RUN apt-get update		    \
    && apt-get install -y	\
    nginx			        \
    sqlite3			        \
    php8.4-fpm		        \
    php8.4-mysql		    \
    php8.4-intl			    \
    php8.4-mbstring		    \
    php8.4-zip		        \
    php8.4-xml		        \
    php8.4-sqlite3          \
    php8.4-curl

# Web server configurations
# Nginx
COPY nginx.conf /etc/nginx/nginx.conf
COPY default /etc/nginx/sites-available/default

# PHP FPM configurations
COPY php.ini /etc/php/8.4/fpm/php.ini
COPY php_cli.ini /etc/php/8.4/cli/php.ini

EXPOSE 80

WORKDIR /var/www/html

CMD service php8.4-fpm start 	\
    && nginx -g 'daemon off;'	\
    && bash
